export default [
  {
    item_name: "Smartphone",
    item_price: 599.99,
    item_code: "SPH001",
    item_seller: "ElectroTech",
  },
  {
    item_name: "Laptop",
    item_price: 899.99,
    item_code: "LTP002",
    item_seller: "GigaMall",
  },
  {
    item_name: "Headphones",
    item_price: 99.99,
    item_code: "HPN003",
    item_seller: "SoundWave",
  },
  {
    item_name: "Tablet",
    item_price: 299.99,
    item_code: "TBL004",
    item_seller: "TechWorld",
  },
  {
    item_name: "Smartwatch",
    item_price: 199.99,
    item_code: "SWT005",
    item_seller: "GadgetZone",
  },
  {
    item_name: "Camera",
    item_price: 449.99,
    item_code: "CMR006",
    item_seller: "SnapShot",
  },
  {
    item_name: "Gaming Console",
    item_price: 399.99,
    item_code: "GCN007",
    item_seller: "GameEmpire",
  },
  {
    item_name: "Wireless Mouse",
    item_price: 29.99,
    item_code: "MS008",
    item_seller: "TechHive",
  },
  {
    item_name: "External Hard Drive",
    item_price: 129.99,
    item_code: "HD009",
    item_seller: "DataDepot",
  },
  {
    item_name: "Fitness Tracker",
    item_price: 79.99,
    item_code: "FT010",
    item_seller: "FitGear",
  },
  {
    item_name: "Bluetooth Speaker",
    item_price: 69.99,
    item_code: "BTS011",
    item_seller: "SoundBar",
  },
  {
    item_name: "Printer",
    item_price: 179.99,
    item_code: "PRT012",
    item_seller: "PrintWorld",
  },
  {
    item_name: "Wireless Earbuds",
    item_price: 129.99,
    item_code: "WEB013",
    item_seller: "AudioTech",
  },
  {
    item_name: "Monitor",
    item_price: 299.99,
    item_code: "MNT014",
    item_seller: "DisplayMart",
  },
  {
    item_name: "Keyboard",
    item_price: 49.99,
    item_code: "KBD015",
    item_seller: "KeyTech",
  },
  {
    item_name: "Router",
    item_price: 89.99,
    item_code: "RT016",
    item_seller: "NetConnect",
  },
  {
    item_name: "Power Bank",
    item_price: 39.99,
    item_code: "PB017",
    item_seller: "ChargeZone",
  },
  {
    item_name: "USB Flash Drive",
    item_price: 19.99,
    item_code: "USB018",
    item_seller: "DataMart",
  },
  {
    item_name: "Projector",
    item_price: 499.99,
    item_code: "PRJ019",
    item_seller: "CineTech",
  },
  {
    item_name: "Desk Lamp",
    item_price: 34.99,
    item_code: "DL020",
    item_seller: "LightWorld",
  },
  {
    item_name: "Wireless Charger",
    item_price: 49.99,
    item_code: "WC021",
    item_seller: "PowerUp",
  },
  {
    item_name: "Webcam",
    item_price: 79.99,
    item_code: "WBC022",
    item_seller: "CamTech",
  },
  {
    item_name: "Smart Plug",
    item_price: 19.99,
    item_code: "SPL023",
    item_seller: "SmartHome",
  },
  {
    item_name: "Portable Speaker",
    item_price: 59.99,
    item_code: "PS024",
    item_seller: "PortableAudio",
  },
  {
    item_name: "E-book Reader",
    item_price: 129.99,
    item_code: "EBR025",
    item_seller: "EbookWorld",
  },
];
